/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ULID.h
 #	source generated by 4D Plugin Wizard
 #	Project : ULID
 #	author : miyako
 #	2025/08/09
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ULID_H
#define PLUGIN_ULID_H

#include "4DPluginAPI.h"


#ifdef __APPLE__
#include <CoreFoundation/CoreFoundation.h>
#else
#include <Windows.h>
#endif

#include <ulid.hh>

#include <iostream>
#include <sstream>
#include <iomanip>
#include <string>
#include <cstdint>

#pragma mark -

static void ULID_from_UUID(PA_PluginParameters params);
static void ULID_to_UUID(PA_PluginParameters params);
static void Generate_ULID(PA_PluginParameters params);

#endif /* PLUGIN_ULID_H */
