/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-ULID.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : ULID
 #	author : miyako
 #	2025/08/09
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-ULID.h"

#pragma mark -

static std::random_device rd;
static std::mt19937 generator(rd());
static std::mutex generator_mutex; // guards `generator`: std::mt19937::operator() is not
                                    // safe to call concurrently from multiple threads,
                                    // and 4D may dispatch plugin commands preemptively.

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- ULID
            
			case 1 :
                ULID_from_UUID(params);
				break;
            case 2 :
                ULID_to_UUID(params);
                break;
            case 3 :
                Generate_ULID(params);
                break;
            case 4 :
                ULID_Get_timestamp(params);
                break;
            case 5 :
                ULID_Set_timestamp(params);
                break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

typedef std::basic_string<PA_Unichar> CUTF16String;

static void fromUstr(CUTF16String& u16, std::string& u8) {
    
#ifdef _WIN32
    int len = WideCharToMultiByte(CP_UTF8, 0, (LPCWSTR)u16.c_str(), u16.length(), NULL, 0, NULL, NULL);
    
    if(len){
        std::vector<uint8_t> buf(len + 1);
        if(WideCharToMultiByte(CP_UTF8, 0, (LPCWSTR)u16.c_str(), u16.length(), (LPSTR)&buf[0], len, NULL, NULL)){
            // Explicit-length constructor: relying on the null-terminated
            // constructor here would silently truncate at the first embedded
            // NUL byte, which the accidental zero-init of buf's extra slot
            // masked for ordinary text but not for input containing one.
            u8 = std::string((const char *)&buf[0], (size_t)len);
        }
    }else{
            u8 = std::string((const char *)"");
    }
#else
    CFStringRef str = CFStringCreateWithCharacters(kCFAllocatorDefault, (const UniChar *)u16.c_str(), u16.length());
    if(str){
        
        size_t size = CFStringGetMaximumSizeForEncoding(CFStringGetLength(str), kCFStringEncodingUTF8) + sizeof(uint8_t);
        std::vector<uint8_t> buf(size);
        CFIndex len = 0;
        CFStringGetBytes(str, CFRangeMake(0, CFStringGetLength(str)), kCFStringEncodingUTF8, 0, true, (UInt8 *)&buf[0], size, &len);

        u8 = std::string((const char *)&buf[0], len);
        CFRelease(str);
    }
#endif
}

static void toUstr(std::string& u8, CUTF16String& u16) {
    
#ifdef _WIN32
    int len = MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)u8.c_str(), u8.length(), NULL, 0);
    
    if(len){
        std::vector<uint8_t> buf((len + 1) * sizeof(PA_Unichar));
        if(MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)u8.c_str(), u8.length(), (LPWSTR)&buf[0], len)){
            // Explicit-length constructor -- see note in fromUstr above.
            u16 = CUTF16String((const PA_Unichar *)&buf[0], (size_t)len);
        }
    }else{
        u16 = CUTF16String((const PA_Unichar *)L"");
    }
    
#else
    CFStringRef str = CFStringCreateWithBytes(kCFAllocatorDefault, (const unsigned char *)u8.c_str(), u8.length(), kCFStringEncodingUTF8, true);
    if(str){
        CFIndex len = CFStringGetLength(str);
        std::vector<uint8_t> buf((len+1) * sizeof(PA_Unichar));
        CFStringGetCharacters(str, CFRangeMake(0, len), (UniChar *)&buf[0]);
        u16 = CUTF16String((const PA_Unichar *)&buf[0]);
        CFRelease(str);
    }
#endif
}

static uint8_t hexCharToValue(char c) {
    
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    
    return 0;
}

static std::string bytesToHex(const std::vector<uint8_t> &data) {
    static const char* hexDigits = "0123456789abcdef";
    std::string out(data.size() * 2, '0');
    for (size_t i = 0; i < data.size(); i++) {
        out[i*2]     = hexDigits[data[i] >> 4];
        out[i*2 + 1] = hexDigits[data[i] & 0x0F];
    }
    return out;
}

static std::array<uint8_t, 16> hexToBytes(const std::string &hex) {
 
    std::array<uint8_t, 16> bytes{};
    
    if (hex.size() == 32) {
        for (size_t i = 0; i < 16; i++) {
            uint8_t high = hexCharToValue(hex[2 * i]);
            uint8_t low  = hexCharToValue(hex[2 * i + 1]);
            bytes[i] = (high << 4) | low;
        }
    }
    
    return bytes;
}

static const char *CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

static int decode_crockford_char(char c) {
    const char *p = strchr(CROCKFORD_ALPHABET, c);
    return p ? (int)(p - CROCKFORD_ALPHABET) : -1;
}

// --- Input validation --------------------------------------------------
// The vendored ulid library's Unmarshal()/UnmarshalFrom() (ulid_struct.hh /
// ulid_uint128.hh) do NOT validate length or character range: they index a
// 26-character buffer and a 256-entry decode table unconditionally. Any 4D
// method can call "ULID to UUID", "ULID Get timestamp", or "ULID Set timestamp"
// with an arbitrary string, so this plugin must reject bad input itself
// before calling into the library -- the library will not do it for us.

static bool isValidHex32(const std::string &hex) {
    if (hex.size() != 32) return false;
    for (unsigned char c : hex) {
        bool isHexDigit = (c >= '0' && c <= '9') ||
                           (c >= 'a' && c <= 'f') ||
                           (c >= 'A' && c <= 'F');
        if (!isHexDigit) return false;
    }
    return true;
}

static bool isValidULIDString(const std::string &str) {
    if (str.size() != 26) return false;
    for (unsigned char c : str) {
        // Reject anything outside 7-bit ASCII before it ever reaches the
        // library's dec[256] lookup table: on a signed-char platform, a byte
        // >= 0x80 becomes a NEGATIVE index into that table when the library
        // does dec[int(str[i])] -- an out-of-bounds read, not just "invalid
        // input". Checking here avoids ever handing such a byte to the library.
        if (c > 0x7F) return false;
        if (decode_crockford_char((char)c) < 0) return false;
    }
    return true;
}

static void ULID_from_UUID(PA_PluginParameters params) {

    CUTF16String returnValue; // stays empty if input is invalid or an exception occurs

    try {
        PA_Unistring *ustr = PA_GetStringParameter(params, 1);
        CUTF16String u16((const PA_Unichar *)ustr->fString, (PA_long32)ustr->fLength);
        std::string u8;
        fromUstr(u16 ,u8);

        if (isValidHex32(u8)) {
            std::array<uint8_t, 16> bytes = hexToBytes(u8);
            std::vector<uint8_t> vec(bytes.begin(), bytes.end());

            std::string str = ulid::Marshal(ulid::UnmarshalBinary(vec));
            toUstr(str, returnValue);
        }
        // else: not a 32-hex-char UUID -- return empty string rather than
        // silently marshaling the ULID for 16 zero bytes.
    }
    catch (...) {
        // Fall through with an empty returnValue -- see note at top of file:
        // every handler must still call PA_Return* on every path, or a host
        // that expects a return value can hang waiting for one that never comes.
    }

    PA_ReturnString(params, (PA_Unichar *)returnValue.c_str());
}

static void ULID_to_UUID(PA_PluginParameters params) {

    CUTF16String returnValue; // stays empty if input is invalid or an exception occurs

    try {
        PA_Unistring *ustr = PA_GetStringParameter(params, 1);
        CUTF16String u16((const PA_Unichar *)ustr->fString, (PA_long32)ustr->fLength);
        std::string u8;
        fromUstr(u16 ,u8);

        if (isValidULIDString(u8)) {
            ulid::ULID ulid = ulid::Unmarshal(u8);

            std::vector<uint8_t> bytes = ulid::MarshalBinary(ulid);
            std::string str = bytesToHex(bytes);

            toUstr(str, returnValue);
        }
        // else: not a well-formed 26-char ULID string -- return empty string.
        // (ulid::Unmarshal performs no length/range checking itself and will
        // read out of bounds on anything shorter than 26 chars, so this check
        // must happen here, before the call.)
    }
    catch (...) {
        // See note in ULID_from_UUID above.
    }

    PA_ReturnString(params, (PA_Unichar *)returnValue.c_str());
}

static void Generate_ULID(PA_PluginParameters params) {

    CUTF16String returnValue;

    try {
        ulid::ULID ulid;
        ulid::EncodeTimeSystemClockNow(ulid);
        {
            std::lock_guard<std::mutex> lock(generator_mutex);
            ulid::EncodeEntropyMt19937(generator, ulid);
        }

        std::string str = ulid::Marshal(ulid);
        toUstr(str, returnValue);
    }
    catch (...) {
        // See note in ULID_from_UUID above.
    }

    PA_ReturnString(params, (PA_Unichar *)returnValue.c_str());
}

/*
static uint64_t ulid_decode_timestamp_ms(std::string& str) {
        
    if (str.length() < 10) return 0;
    
    uint64_t total = 0;
    
    // Each char = 5 bits; first 10 chars = 50 bits total
    for (int i = 0; i < 10; i++) {
        int val = decode_crockford_char(str.at(i));
        if (val < 0) return 0;
        total = (total << 5) | (uint64_t)val;

        std::cout << "Step " << i << ": char='" << str[i] << "' val=" << val
                         << " total=0x" << std::hex << total << std::dec << " (" << total << ")\n";
           
    }
    
    // Timestamp is the top 48 bits; discard the lowest 2 bits
    return total >> 2;
}
*/

static std::string ms_to_iso8601(uint64_t ms) {

    time_t t = (time_t)(ms / 1000);
    long msec = (long)(ms % 1000);

    struct tm tm_utc = {};

#if defined(_WIN32)
    // gmtime_s returns 0 on success, non-zero (errno_t) on failure -- e.g. if
    // `t` is out of the range this platform can represent as a broken-down time.
    if (gmtime_s(&tm_utc, &t) != 0) return "";
#else
    // gmtime_r returns NULL on failure and does not guarantee tm_utc is left
    // in a defined state -- using tm_utc afterwards on failure would be
    // undefined behavior, so bail out immediately instead.
    if (gmtime_r(&t, &tm_utc) == nullptr) return "";
#endif
    
    char tm_str[20];//19+1
    if(strftime(tm_str, sizeof(tm_str), "%Y-%m-%dT%H:%M:%S", &tm_utc) == 19){
        char iso_str[25];//24+1
        if(snprintf(iso_str, sizeof(iso_str), "%s.%03ldZ", tm_str, msec) == 24) {
            return std::string(iso_str, sizeof(iso_str));
        }
    }

    return "";
}

static uint64_t ms_to_iso8601_to_ms(const std::string& iso) {
    
    std::tm tm = {};
        int milliseconds = 0;
    
    std::istringstream ss(iso);
    ss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%S");
    
    if (!ss.fail()) {
        // Parse milliseconds if present
            if (ss.peek() == '.') {
                ss.get(); // consume '.'
                char ms_str[4] = {'0', '0', '0', '\0'};
                ss.read(ms_str, 3);
                // std::stoi throws std::invalid_argument if ms_str doesn't
                // start with a digit (e.g. a malformed fractional-seconds
                // field such as ".abcZ"). A 4D caller controls this text
                // directly via "ULID Set timestamp", so guard it here rather
                // than letting the exception propagate to the caller, where
                // PluginMain's catch-all would swallow it without a return
                // value ever having been sent back to 4D.
                try {
                    milliseconds = std::stoi(ms_str);
                } catch (...) {
                    milliseconds = 0;
                }
            }
        
        // Assume 'Z' at end (UTC)
        // Convert tm to time_t (seconds since epoch)
#if defined(_WIN32) || defined(_WIN64)
        time_t time_sec = _mkgmtime(&tm);
#else
        time_t time_sec = timegm(&tm);
#endif

        if (time_sec != -1) {
            return static_cast<int64_t>(time_sec) * 1000 + milliseconds;
        }
    }
    
    return 0;
}

static void ULID_Get_timestamp(PA_PluginParameters params) {

    CUTF16String returnValue; // stays empty if input is invalid or an exception occurs

    try {
        PA_Unistring *ustr = PA_GetStringParameter(params, 1);
        CUTF16String u16((const PA_Unichar *)ustr->fString, (PA_long32)ustr->fLength);
        std::string u8;
        fromUstr(u16 ,u8);

        if (isValidULIDString(u8)) {
            ulid::ULID ulid = ulid::Unmarshal(u8);
            time_t ms = ulid::Time(ulid);//not really time_t; milliseconds since epoch

            std::string str = ms_to_iso8601(ms);
            toUstr(str, returnValue);
        }
        // else: not a well-formed 26-char ULID string -- return empty string.
    }
    catch (...) {
        // See note in ULID_from_UUID above.
    }

    PA_ReturnString(params, (PA_Unichar *)returnValue.c_str());
}

static void ULID_Set_timestamp(PA_PluginParameters params) {

    CUTF16String returnValue; // stays empty if input is invalid or an exception occurs

    try {
        PA_Unistring *ustr = PA_GetStringParameter(params, 2);
        CUTF16String u16((const PA_Unichar *)ustr->fString, (PA_long32)ustr->fLength);
        std::string u8;
        fromUstr(u16 ,u8);

        time_t ms = (time_t)ms_to_iso8601_to_ms(u8);

        ustr = PA_GetStringParameter(params, 1);
        u16 = CUTF16String((const PA_Unichar *)ustr->fString, (PA_long32)ustr->fLength);
        fromUstr(u16 ,u8);

        if (isValidULIDString(u8)) {
            ulid::ULID ulid = ulid::Unmarshal(u8);
            ulid::EncodeTime(ms, ulid);

            std::string str = ulid::Marshal(ulid);
            toUstr(str, returnValue);
        }
        // else: not a well-formed 26-char ULID string -- return empty string.
    }
    catch (...) {
        // See note in ULID_from_UUID above.
    }

    PA_ReturnString(params, (PA_Unichar *)returnValue.c_str());
}
